name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - name: Install deps
        run: |
          pip install numpy<2 scipy gymnasium==0.29.1 matplotlib pytest
          pip install torch==2.2.2+cpu
          pip install stable-baselines3==2.3.1
          pip install -e .
      - name: Run tests
        run: pytest -q
